### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Th3-A6add0n** [BlissRoms/platform_manifest#8]
`build/make/core/product_config.mk:234: error: Can not locate config makefile for product "android_x86_64".
16:30:38 dumpvars failed with: exit status 1`

**Comment by electrikjesus** [comment]
You need to follow the instructions first. Check out the readme

**Comment by electrikjesus** [comment]
$ bash build-x86.sh -s (will also do initial patching)
 $ bash build-x86.sh -r android_x86_64-userdebug

**Comment by Th3-A6add0n** [comment]
> $ bash build-x86.sh -s (will also do initial patching)
> $ bash build-x86.sh -r android_x86_64-userdebug

Thanks but this game me the same error

**Comment by electrikjesus** [comment]
Then there's something you are missing even before you get to that step

**Comment by Th3-A6add0n** [comment]
> Then there's something you are missing even before you get to that step

ok I'll try again

**Comment by electrikjesus** [comment]
If you run into more issues, ask for help in our Telegram chat for Bliss OS. • TΞAM • BLISS • OS for PCs (x86) Help
Team Bliss is proud to present Bliss OS which is Android Bliss'd out for x86 Desktops and Laptops
https://t.me/blissx86
