### ISSUE TITLE
Problem at build because of configs for a kernel

### ISSUE THREAD

**Issue by Peryn** [BlissRoms/platform_manifest#9]
At build the error takes off:
`[1035/1035] including vendor/xiaomi/msm8953-common/Android.mk ...
test/vts/tools/build/tasks/vts_package.mk:141: error: FindEmulator: cd: kernel/configs: No such file or directory
21:50:44 ckati failed with: exit status 1`
The error crashes due to the lack of the configs folder in the kernel folder in the source.
The problem is solved by simply downloading the configs folder from Google’s sources:
`git clone https://android.googlesource.com/kernel/configs configs`
Please add this folder initially to the source, not everyone can guess where to get this folder.

**Comment by Jackeagle** [comment]
It does exist in source 
Ref Link : https://github.com/BlissRoms/platform_manifest/blob/p9.0/default.xml#L502
